# Jekyll configuration for GitHub Pages portfolio
title: "Yoshiki Katayama"
description: "Full-Stack Web Developer passionate about creating innovative web solutions that solve real-world problems"
author: "YK4651"
email: "your-email@example.com"
url: "https://YK4651.github.io"
baseurl: ""

# Build settings
markdown: kramdown
highlighter: rouge
theme: minima

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Collections
collections:
  projects:
    output: true
    permalink: /:collection/:name/

# Exclude files
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Social media links (optional)
github_username: YK4651
# twitter_username: your_twitter
# linkedin_username: your_linkedin

# Multi-language support
languages: ["ja", "en"]
default_lang: "ja"
exclude_from_localization: ["assets", "admin"]

# Navigation
navigation:
  - title: Home
    url: /
  - title: About
    url: /about/
  - title: Projects
    url: /projects/
  - title: Contact
    url: /contact/
